FROM mqt0029/ros2-tutorial:latest

# see https://github.com/microsoft/wslg/blob/main/samples/container/Containers.md#containerized-applications-access-to-the-vgpu
ENV LIBVA_DRIVER_NAME d3d12
ENV LD_LIBRARY_PATH /usr/lib/wsl/lib
